[base]
language = ru
timezone = Europe/Moscow
log.level = info
#log.file = app.log
log.color = on
log.filter = !sqlx, !actix, !mio

[db]
url = postgresql:///?user=app&password=123456&host=/var/run/postgresql&dbname=app&sslmode=disable
schema = app,api,anon,auth,public
max_conn = 100
acquire_timeout = 1

[tokio]
threads = 4

[actix]
threads = 4
listen = 0.0.0.0
port = 80
