[package]
name = "app-web"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
path = "src/lib.rs"
name = "app_web"
crate-type = ["lib"]

[features]

[dependencies]
app-base = { workspace = true, features = ["std"] }
app-async = { workspace = true, features = ["db"] }
tokio = { workspace = true }
actix = { workspace = true }
actix-web = { workspace = true }
actix-http = { workspace = true }
actix-cors = { workspace = true }
actix-ws = { workspace = true }
actix-files = { workspace = true }
actix-multipart = { workspace = true }
actix-web-grants = { workspace = true }
jsonwebtoken = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
validator = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
dashmap = { workspace = true }
itoa = { workspace = true }
bytes = { workspace = true }
regex = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
accessory = { workspace = true }
md5 = { workspace = true }
tera = { workspace = true }
flate2 = { workspace = true }
base64 = { workspace = true }
glob = { workspace = true }
ahash = { workspace = true }

[dev-dependencies]
app-testing = { workspace = true }
